### PR TITLE
Development & build process fix and various other amendments (2nd attempt)

### PR DESCRIPTION
**Pull request by chrisdwheatley**
This changes the overall structure of the project, hence the difficult to de-construct diff. I've been pushing to my own gh-pages to test, you can view it here - http://swirlycheetah.github.io/hood.ie/ (some links won't work due to the url structure difference but you can still get to them manually).

Although this is a merge with the gh-pages branch it'll in effect need to be merged/copied over to master and then the gh-pages branch removed as that'll just be used for the deploy process.

I rebased as per @gr2m's request but it seems to have duplicated my commits, not quite sure if that's expected behaviour or my incompetence =\ If that can be tidied up I'll happily do it.

A list of amendments:
- [x] deploy with grunt-gh-pages (#43)
- [x] remove various un-required files
- [x] amend intro page installation instructions (#46)
- [x] replace Gregor's image (#33)
- [x] added a coming soon merchandise section (#48)
- [x] update readme with build/deploy process
- [x] add subtitle to title tag
- [x] remove .html from links

Other things which could be worth doing:
- [ ] serve static files from CDN (can be done for free with Cloudflare)
- [ ] concat vendor css & js in with hoodie files, e.g. jQuery & Mailchimp
- [ ] E2E testing with http://nightwatchjs.org/

### CODE REVIEW

**Comment by svnlto** [comment]
this is huge.

also, +1000 on:

> serve static files from CDN (can be done for free with Cloudflare)
> concat vendor css & js in with hoodie files, e.g. jQuery & Mailchimp

**Comment by espy** [comment]
wow

Wow! Impressive! Thank you so much! That's a massive improvement, and it all looks excellent so far. I'll take a closer look later today, just to get my bearings again :) 

Thanks for all the work you put into this!

**Comment by chrisdwheatley** [comment]
Thanks for the kind words =)

The main culprit in the size of this PR is the removal of the node_modules directory, which is currently committed into the repo, if you don't take that into account it's just some folder restructure, a build process and a few small tweaks.

Using a CDN for static content on gh-pages is especially useful as you have no control over the cache headers and their default is only 10 minutes, see http://www.webpagetest.org/performance_optimization.php?test=140218_KV_95S&run=1&cached=0.

**Comment by espy** [comment]
Right, I just merged it manually, somehow managed to miss your CNAME commit in the process and therefore took the site down for a couple of minutes, but that was easily fixed :) 

Thanks again, `grunt deploy` is a joy to use :)

**Comment by chrisdwheatley** [comment]
Thanks Alex, yeah I made a slight error with the CNAME location and was frantically asking someone to add it in manually on IRC until my request got merged, looks like you had it under control though. I only committed the change a few minutes ago so thats probably why it got missed.

I'll send over a fresh PR shortly to change the location of the CNAME file and robots.txt to be under the src directory, this'll save having to add files manually to the grunt shell `cp` command.

**Comment by espy** [comment]
Oh dear, sorry about that, I should definitely be in there more often. Also: good point, that makes much more sense that what I just did :D

**Pull request closed without merging**
