### PR TITLE
Add installation instructions for all platforms

### PR DESCRIPTION
**Pull request by caolan**
When I do "grunt build" and "grunt server" I don't seem to have working stylesheets, so I have no idea what this actually looks like! Please review before publishing!

Wait for review regarding instructions for non-Linux platforms too please.

### CODE REVIEW

**Comment by caolan** [comment]
@janl please can you review the OS X installation instructions and make sure they are correct?
@mdlawson can you please review the Windows installation instructions? I haven't actually tested this ;)

**Comment by mdlawson** [comment]
@caolan: The instructions look fine, but at the very least [this pull](https://github.com/hoodiehq/node-multicouch/pull/9) needs to go into node-multicouch, theres a couple of commits [here](https://github.com/mdlawson/hoodie-app/commits/master) that are "quick fixes" for things that need to be implemented for windows (should probably just be done properly fron scratch, hence no pull), and the local-tld stuff still needs to all be sorted out, before it will actually work.
Could also point out that couchdb needs to be installed to the default location on windows, or manually added to the path.

**Comment by janl** [comment]
Looks good. I have a few more patches in the pipeline that make things a little easier, but I’ll adjust the docs accordingly later.

Can you make the same edits to `my-first-hoodie/README.md` (or remove them altogether and link to the website, so we don’t have to dupe docs)

**Comment by janl** [comment]
@gr2m @espy could you merge this? my setup is still fubar.

**Comment by janl** [comment]
Also, @espy this needs docs for how to run `jekyll --server` locally

**Comment by janl** [comment]
Also, point `my-first-hoodie/README.md` to http://hood.ie/#installation and close my-first-hoodie/pull/13 when this goes live.

**Comment by espy** [comment]
Merged, updated the my-first-hoodie readme, and closed issue 13 over there. 

I'm not even using Jekyll myself atm, still have to get that running.

**Pull request merged**
